name: Check packages with clang-format

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: './packages/muelu ./packages/tempus ./packages/teko ./packages/xpetra'
        exclude: './packages/tempus/examples'
        extensions: 'cpp,hpp'
        clangFormatVersion: 14
        inplace: true
    - run: git diff HEAD > format_patch.txt
    - run: if [ "$(cat format_patch.txt)" == "" ] ; then rm format_patch.txt ; else cat format_patch.txt; fi

    - uses: actions/upload-artifact@v4
      id: upload-artf
      if: ${{ hashFiles('format_patch.txt') != '' }}
      with:
        name: clang format patch
        path: format_patch.txt

    - name: Artifact ID test
      run: |
        echo "Artifact ID is ${{ steps.upload-artf.outputs.artifact-id }}"
        echo "Link: ${{ steps.upload-artf.outputs.artifact-url }}"

    # This does not work for PRs from forks.
    - name: Post artifact in issue comment
      uses: mshick/add-pr-comment@v2.8.1
      if: ${{ (hashFiles('format_patch.txt') != '') && (github.event.pull_request.head.repo.full_name == github.repository) }}
      with:
        message: |
          Your PR updated files that did not respect package clang formatting settings.  Please apply the patch found [here](${{ steps.upload-artf.outputs.artifact-url }})

    - uses: actions/github-script@v3
      if: ${{ hashFiles('format_patch.txt') != '' }}
      with:
        script: |
          core.setFailed('Your PR updated files that did not respect package clang formatting settings. Please download and apply the formatting patch! It is located at the bottom of the summary tab for this workflow and at this link: ${{ steps.upload-artf.outputs.artifact-url }}')
