name: Check MPI_COMM_WORLD

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      with:
        fetch-depth: 0

    - name: Search for MPI_COMM_WORLD in modified lines
      run: |
        python $GITHUB_WORKSPACE/commonTools/test/utilities/check-mpi-comm-world-usage.py \
        --base origin/${{ github.event.pull_request.base.ref }} \
        --head ${{ github.event.pull_request.head.sha }}
